//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public Airplane()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID_Airplane { get; set; }
        public System.DateTime Date_of_service { get; set; }
        public string Number_of_seats { get; set; }
        public string Speed { get; set; }
        public string Fuel_reserve { get; set; }
        public int ID_Equipment { get; set; }
        public string Name { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
