//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Awards
    {
        public Awards()
        {
            this.Salary = new HashSet<Salary>();
        }
    
        public int ID_Awards { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ICollection<Salary> Salary { get; set; }
    }
}
