//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID_Clients { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string E_mail { get; set; }
        public decimal Number { get; set; }
        public int ID_Ticket { get; set; }
        public int ID_User { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual User User { get; set; }
    }
}
