//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Airplane = new HashSet<Airplane>();
        }
    
        public int ID_Equipment { get; set; }
        public System.DateTime Date_of_service { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Airplane> Airplane { get; set; }
    }
}
