//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ID_Flight { get; set; }
        public int ID_Airplane { get; set; }
        public int ID_End { get; set; }
        public System.DateTime Data_time { get; set; }
        public string Time_flight { get; set; }
        public System.DateTime Start__of_registration { get; set; }
        public System.DateTime Boarding_on_board { get; set; }
        public int ID_Status_F { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual City_end City_end { get; set; }
        public virtual Status_Flight Status_Flight { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
