//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        private static Entities2 _context;

        public static Entities2 GetContext()
        {
            if (_context == null)
            {
                _context = new Entities2();
            }
            return _context;
        }
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Airplane> Airplane { get; set; }
        public DbSet<Awards> Awards { get; set; }
        public DbSet<City_end> City_end { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Discount> Discount { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Flight> Flight { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Salary> Salary { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<Status_Flight> Status_Flight { get; set; }
        public DbSet<Status_S> Status_S { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Taxes> Taxes { get; set; }
        public DbSet<Tickets> Tickets { get; set; }
        public DbSet<User> User { get; set; }
    }
}
