//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public Salary()
        {
            this.Staff = new HashSet<Staff>();
        }
    
        public int ID_Salary { get; set; }
        public int ID_Status_S { get; set; }
        public decimal Salary1 { get; set; }
        public int ID_Taxes { get; set; }
        public int ID_Awards { get; set; }
    
        public virtual Awards Awards { get; set; }
        public virtual Status_S Status_S { get; set; }
        public virtual Taxes Taxes { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
