//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID_Staff { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string E_mail { get; set; }
        public string Number { get; set; }
        public int ID_User { get; set; }
        public int ID_Salary { get; set; }
        public int ID_Status_S { get; set; }
    
        public virtual Salary Salary { get; set; }
        public virtual Status_S Status_S { get; set; }
        public virtual User User { get; set; }
    }
}
