//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Flight
    {
        public Status_Flight()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID_Status_F { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
