//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_S
    {
        public Status_S()
        {
            this.Salary = new HashSet<Salary>();
            this.Staff = new HashSet<Staff>();
        }
    
        public int ID_Status_S { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Salary> Salary { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
