//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public Tickets()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int ID_Ticket { get; set; }
        public int Quantity_tickets { get; set; }
        public int ID_Discount { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Data_time { get; set; }
        public int ID_Flight { get; set; }
        public int ID_Class { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
