//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Clients = new HashSet<Clients>();
            this.Staff = new HashSet<Staff>();
        }
    
        public int ID_User { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Role { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
